Repository payara/Payara, pull requests merged in 2018-11, with the labels that each got.

#3385 PAYARA-3241 Only display the MicroProfile HealthChecker on Server Config
  appserver/admingui/healthcheck-service-console-plugin/src/main/resources/healthcheck/healthcheckConfigTabs.inc
Labels: v:Payara-5

#3378 PAYARA-3239 ClassNotFoundException in Payara Embedded
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/payara-appserver-modules/healthcheck-checker/pom.xml
Labels: v:Payara-5

#3334 PAYARA-3085 Support global configuration during application deployment
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
Labels: CLA, community-contribution

#3344 Fix to issue PAYARA-3186: Small null guard added in the case current …
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java
Labels: v:Payara-5

#3372 PAYARA-3231 It appears that with Firefox 63, that the Payara admin web screens no longer work correctly
  appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ja.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ko.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_CN.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_TW.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_ja.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_ko.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_zh_CN.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_zh_TW.css
  appserver/pom.xml
Labels: v:Payara-5

#3384 PAYARA-3233 When deploying an application in the admin console all further deployment options are no longer shown
  appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml
  appserver/pom.xml
Labels: v:Payara-5

#3375 PAYARA-3222 MetricProducer Cannot Be Final
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/producer/MetricProducer.java
Labels: v:Payara-5

#3183 Fixing sonar blocker bugs with class CircuitBreakerState
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/RetryInterceptor.java
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/state/CircuitBreakerState.java
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/state/StateTime.java
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/state/CircuitBreakerStateTest.java
Labels: CLA, community-contribution, v:Payara-5

#3206 Fixing sonar blocker bugs in module core servlet container
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/AuthenticatorBase.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/DigestAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java
  appserver/web/web-core/src/main/java/org/apache/catalina/fileupload/Multipart.java
  appserver/web/web-core/src/main/java/org/apache/catalina/servlets/WebdavServlet.java
  appserver/web/web-core/src/main/java/org/apache/catalina/session/FileStore.java
  appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardSession.java
  appserver/web/web-core/src/main/java/org/apache/catalina/startup/Catalina.java
  appserver/web/web-core/src/main/java/org/apache/catalina/startup/ExpandWar.java
  appserver/web/web-core/src/main/java/org/apache/catalina/startup/PasswdUserDatabase.java
Labels: CLA, community-contribution

#3350 PAYARA-3244 Fixing windows specific bug in JSR-109 module
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java
Labels: CLA, community-contribution, v:Payara-5

#3373 PAYARA-3199 Add null check for bootstrap of metrics
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
Labels: v:Payara-5

#3342 PAYARA-3245 Replacing StringBuffer with StringBuilder in module amx-core
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/core/PathnameParser.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/PathnamesImpl.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/ToolsImpl.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/ExceptionUtil.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/LineReaderImpl.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/MapUtil.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/RegexUtil.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/StringUtil.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/JMXUtil.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/MBeanInterfaceGenerator.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/AttributeChangeNotificationStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/CompositeDataStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/MBeanServerNotificationStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/MonitorNotificationStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/NotificationStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/ObjectNameStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/TabularDataStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/stringifier/IteratorStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/stringifier/IteratorStringifierBase.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/stringifier/ProviderStringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/stringifier/Stringifier.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/stringifier/X509CertificateStringifier.java
Labels: CLA, community-contribution, v:Payara-5

#3399 Updated Weld Version to 3.0.5.Final.payara-p1
  appserver/pom.xml
Labels: v:Payara-5

#3419 Fixes linkage error concurrently loading remote EJBs
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
Labels: CLA, community-contribution

#3379 PAYARA-3171 custom keystore
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLImpl.java
  nucleus/security/core/src/test/java/com/sun/enterprise/security/ssl/GlassfishSSLImplTest.java
Labels: v:Payara-4

#3414 PAYARA-3247 Add NPN Version Switch
  appserver/admin/gf_template/src/main/resources/config/domain.xml
  appserver/admin/gf_template_web/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
  appserver/extras/embedded/all/src/main/resources/config/domain.xml
  appserver/extras/embedded/web/src/main/resources/config/domain.xml
  nucleus/admin/template/src/main/resources/config/domain.xml
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java
  nucleus/packager/nucleus-grizzly/pom.xml
  nucleus/packager/nucleus-grizzly/src/main/assembly/nucleus-grizzly.xml
Labels: v:Payara-5

#3407 PAYARA-3250 move AutoDeployer thread onto the Scheduled Payara Executor Service
  nucleus/deployment/autodeploy/pom.xml
  nucleus/deployment/autodeploy/src/main/java/org/glassfish/deployment/autodeploy/AutoDeployService.java
Labels: Action Required

#3420 Payara 3046 listing cache keys not working
  appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/implementation/PayaraGeneratedCacheKey.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ListCacheKeys.java
Labels: v:Payara-5

#3403 PAYARA-3248-Upgrade-hazelcast-to-3.11 - Payara4
  nucleus/pom.xml
Labels: v:Payara-4

#3400 PAYARA-3090 Support BASIC authentication with additional micro repositories - Payara4
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/DeployerImpl.java
  nucleus/deployment/common/src/main/java/fish/payara/deployment/util/GAVConvertor.java
Labels: v:Payara-4

#3341 PAYARA-2905 Prevent creation of databases used for Timer Service when only non-persistent timers are present - Payara4
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EjbNamingReferenceManagerImpl.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/AbstractSessionContextImpl.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerServiceWrapper.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/NonPersistentEJBTimerService.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/SessionContextImpl.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/SingletonContextImpl.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/TimerServiceNamingProxy.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/TimerWrapper.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/admin/cli/ListTimers.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/admin/cli/MigrateTimers.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/annotation/handlers/AbstractEjbHandler.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbDeployer.java
  appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/MessageBeanContextImpl.java
  appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/DistributedEJBTimerService.java
  appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/PersistentEJBTimerService.java
  appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/TimerBean.java
  appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/TimerState.java
  appserver/ejb/ejb-timer-service-app/src/main/java/com/sun/ejb/timers/TimerWelcomeServlet.java
  appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
  appserver/persistence/entitybean-container/src/main/java/org/glassfish/persistence/ejb/entitybean/container/EntityContextImpl.java
Labels: v:Payara-4

#3336 PAYARA-2479 PAYARA-3118 MP health check checker - Payara4
  appserver/admingui/healthcheck-service-console-plugin/src/main/resources/fish/payara/admingui/healthcheck/Strings.properties
  appserver/admingui/healthcheck-service-console-plugin/src/main/resources/healthcheck/checkers/mphealthcheckConfiguration.jsf
  appserver/admingui/healthcheck-service-console-plugin/src/main/resources/healthcheck/healthcheckConfigTabs.inc
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/packager/microprofile-package/pom.xml
  appserver/payara-appserver-modules/healthcheck-checker/pom.xml
  appserver/payara-appserver-modules/healthcheck-checker/src/main/java/fish/payara/healthcheck/mphealth/HealthCheckTimeoutExecutionOptions.java
  appserver/payara-appserver-modules/healthcheck-checker/src/main/java/fish/payara/healthcheck/mphealth/MicroProfileHealthChecker.java
  appserver/payara-appserver-modules/healthcheck-checker/src/main/java/fish/payara/healthcheck/mphealth/SetMicroProfileHealthCheckerConfiguration.java
  appserver/payara-appserver-modules/pom.xml
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckConstants.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/GetHealthCheckConfiguration.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigurer.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/CheckerType.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/MicroProfileHealthCheckerConfiguration.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/LocalStrings.properties
Labels: v:Payara-4

#3401 PAYARA-3225-Location-Header-Not-Present-with-WebApplicationException - Payara4
  appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingExceptionMapper.java
Labels: v:Payara-4

#3366 PAYARA-3062 Support MySQL 8 connector in admin console - Payara4
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/cpds.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/dbvendor.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/ds.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/validationclassnames.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/xads.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/templates/resources/jdbc/mysql8_type4_datasource.xml
  appserver/tests/embedded/mysql/src/main/java/org/glassfish/tests/embedded/web/MySqlTestServlet.java
  appserver/tests/paas/multiple-db-app-scoped-services/advanced/src/main/webapp/WEB-INF/glassfish-resources.xml
  appserver/tests/paas/multiple-db-app-scoped-services/basic/src/main/webapp/WEB-INF/glassfish-resources.xml
  appserver/tests/paas/multiple-db-shared-services/advanced/src/main/webapp/WEB-INF/glassfish-resources.xml
  appserver/tests/paas/multiple-db-shared-services/basic/src/main/webapp/WEB-INF/glassfish-resources.xml
Labels: v:Payara-4

#3422 PAYARA-3265 Fixing linkage errors with generated classes (Part 2)
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
Labels: v:Payara-5

#3310 PAYARA-3266 Using environment variable in logging.properties
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfig.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/PropertyPlaceholderHelper.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/util/PropertyPlaceholderHelperTest.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogFacade.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/ListLogAttributes.java
Labels: CLA, community-contribution

#3409 PAYARA-3252 refactor the healthcheck service to use the Payara Executor Service
  nucleus/payara-modules/healthcheck-core/pom.xml
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java
  nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java
Labels: Action Required

#3428 PAYARA-3199 Add null check for bootstrap of metrics - Payara4
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
Labels: v:Payara-4

#3429 Payara 3212 Increase performance of large EAR deployments -Payara4
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
Labels: v:Payara-4

#3404 PAYARA-3240 Cleanup sonar warnings for nucleus/cluster/admin - Payara4
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/BootstrapSecureAdminCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ClusterCommandHelper.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CopyConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeImplicitCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeSshCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateRemoteNodeCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteNodeSshCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ExportSyncBundle.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/GlassFishClusterExecutor.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/InstanceRegisterInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListClustersCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListNodesHelper.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/NodeAgentConfigUpgrade.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/NodeUtils.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/PingNodeRemoteCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/PingNodeSshCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartInstanceInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/SecureAdminBootstrapHelper.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ServerSynchronizer.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/SetupSshCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StartInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopClusterCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopInstanceInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/Strings.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/SynchronizeFiles.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/UpdateNodeCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/UpdateNodeConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/UpdateNodeRemoteCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/UpdateNodeSshCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ValidateDcom.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ValidateNodeCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/dcom/CreateNodeDcom.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/dcom/DeleteNodeDcom.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/dcom/ListNodesDcomCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/dcom/PingNodeDcomCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/dcom/Strings.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/dcom/UpdateNodeDcomCommand.java
Labels: v:Payara-4

#3398 PAYARA-3267 Fixing memory-wastage with JavaEETransactionImpl
  appserver/admin/production_domain_template/src/main/resources/config/domain.xml
  appserver/transaction/internal-api/src/main/java/com/sun/enterprise/transaction/api/TransactionAdminBean.java
  appserver/transaction/jta/pom.xml
  appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionImpl.java
  appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
  nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java
  nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorServiceConfiguration.java
Labels: CLA, community-contribution, v:Payara-5

#3427 PAYARA-3166 Prevent showing of spurious error on command replication - Payara4
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/CreateFileUser.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/DeleteFileUser.java
Labels: v:Payara-4

#3430 PAYARA-3209 Added vendor support for MP-JWT namespaced claims
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
Labels: v:Payara-5

#3421 PAYARA-3046 listing cache keys not working Payara4
  appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/implementation/PayaraGeneratedCacheKey.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ListCacheKeys.java
Labels: v:Payara-4

#3371 PAYARA-3216 Make Weld concurrent bean loading configurable
  appserver/deployment/dol/pom.xml
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/impl/ModuleScanner.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
  appserver/pom.xml
  appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/CDIService.java
  appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java
  appserver/web/weld-integration-fragment/pom.xml
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/ACLSingletonProvider.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/BootstrapConfigurationImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/ExecutorServicesImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/ExternalConfigurationImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
  nucleus/core/kernel/src/test/java/org/glassfish/tests/kernel/deployment/EventsTest.java
  nucleus/core/kernel/src/test/resources/DomainTest.xml
  nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java
Labels: DO NOT MERGE, v:Payara-5

#3439 Reverted System Specific Path Variables
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ServerSynchronizer.java
Labels: v:Payara-5

#3443 Removed Payara Executor Service From Payara 4
  Jenkinsfile-MicroProfile
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/all/src/main/resources/config/domain.xml
  appserver/extras/embedded/web/pom.xml
Labels: v:Payara-4

#3361 INFRA-168 Always collect test results, server logs - Payara4
  Jenkinsfile
  Jenkinsfile-MicroProfile
Labels: v:Payara-4
