Repository payara/Payara, pull requests merged in 2018-04, with the labels that each got.

#2594 Payara 2610 4 branch
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/IdmService.java
  nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
Labels: v:Payara-4

#2593 PAYARA-2610 use SSL keystore passwords from command line for Micro
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/IdmService.java
  nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
Labels: v:Payara-5

#2573 PAYARA-2593 Updated Eclipselink
  appserver/persistence/eclipselink-wrapper/pom.xml
  appserver/pom.xml
Labels: 3:DevInProgress, in development, v:Payara-5

#2603 PAYARA-2657 grizzly race condition for Payara 4
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TargetBasedResolver.java
  nucleus/admin/rest/rest-service/src/main/java/fish/payara/admin/rest/resources/MonitoredAttributeBagResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/LeafResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateListOfResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateRestResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/DomainXmlVerifier.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/DeleteSystemProperty.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/V2DottedNameSupport.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/NetworkListener.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/ThreadPool.java
Labels: 4:Ready, c:ConfirmedBug, upstream bug, v:Payara-4

#2585 PAYARA-2263 per-jdk version domain options
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/InstanceHandler.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/SecurityHandler.java
  appserver/admingui/common/src/main/resources/javaConfig/jvmOptionsTable.inc
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/JvmOptionBag.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/GrizzlyConfigSchemaMigrator.java
  nucleus/admin/config-api/src/test/java/com/sun/enterprise/configapi/tests/JavaConfigSubTypesTest.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/V2ToV3ConfigUpgrade.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/universal/xml/MiniXmlParserTest.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/util/JavaVersionTest.java
  nucleus/core/kernel-l10n/src/main/resources/com/sun/enterprise/v3/admin/commands/LocalStrings_de.properties
  nucleus/core/kernel-l10n/src/main/resources/com/sun/enterprise/v3/admin/commands/LocalStrings_es.properties
  nucleus/core/kernel-l10n/src/main/resources/com/sun/enterprise/v3/admin/commands/LocalStrings_fr.properties
  nucleus/core/kernel-l10n/src/main/resources/com/sun/enterprise/v3/admin/commands/LocalStrings_it.properties
  nucleus/core/kernel-l10n/src/main/resources/com/sun/enterprise/v3/admin/commands/LocalStrings_pt_BR.properties
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/CreateJvmOptions.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/DeleteJvmOptions.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/ListJvmOptions.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/LocalStrings.properties
Labels: 4:Ready, c:Enhancement, v:Payara-5

#2589 PAYARA-2632 add force spin detection system property for Grizzly
  appserver/admin/gf_template/src/main/resources/config/domain.xml
  appserver/admin/gf_template_web/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/payara-boot.properties
Labels: v:Payara-5

#2590 PAYARA-2632 add force spin detection system property for Grizzly v4
  appserver/admin/gf_template/src/main/resources/config/domain.xml
  appserver/admin/gf_template_web/src/main/resources/config/domain.xml
  appserver/admin/payara_template/src/main/resources/config/domain.xml
  appserver/admin/payara_template_web/src/main/resources/config/domain.xml
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/payara-boot.properties
Labels: v:Payara-4

#2599 asadmin to import plain PKCS#8 RSA keypairs into the java keystore
  .gitignore
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/KeystoreManager.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/LocalStrings.properties
  nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/AddKeypairCommand.java
  nucleus/admin/server-mgmt/src/test/java/com/sun/enterprise/admin/servermgmt/KeystoreManagerTest.java
  nucleus/admin/server-mgmt/src/test/resources/com/sun/enterprise/admin/servermgmt/certificate.pem
  nucleus/admin/server-mgmt/src/test/resources/com/sun/enterprise/admin/servermgmt/privatekey.key
  nucleus/admin/server-mgmt/src/test/resources/com/sun/enterprise/admin/servermgmt/sample-store.jks
  nucleus/admin/server-mgmt/src/test/resources/com/sun/enterprise/admin/servermgmt/sample-store.p12
Labels: CLA

#2643 PAYARA-2633 set domain.xml file encoding - Payara 4
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/ServerReaderFilter.java
Labels: 4:Ready, c:Enhancement, in review, v:Payara-4

#2642 PAYARA-2633 set domain.xml file encoding
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/ServerReaderFilter.java
Labels: 4:Ready, c:Enhancement, in review, v:Payara-5

#2659 PAYARA-2697 default context root admin console improvement
  appserver/admingui/common/src/main/resources/js/adminjsf.js
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebDeployer.java
Labels: 4:Ready, c:Enhancement, in review, v:Payara-5

#2650 PAYARA-1394 OAuth 2 client integration
  api/payara-api/pom.xml
  api/payara-api/src/main/java/fish/payara/security/oauth2/annotation/OAuth2AuthenticationDefinition.java
  api/payara-api/src/main/java/fish/payara/security/oauth2/api/OAuth2AccessToken.java
  api/payara-api/src/main/java/fish/payara/security/oauth2/api/OAuth2State.java
  api/payara-api/src/main/java/fish/payara/security/oauth2/api/OAuthIdentityStore.java
  appserver/packager/glassfish-web/pom.xml
  appserver/payara-appserver-modules/pom.xml
  appserver/payara-appserver-modules/security-oauth2/pom.xml
  appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java
  appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2MechanismHandler.java
  appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2Producer.java
  appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2StateHolder.java
  appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/package-info.java
  appserver/payara-appserver-modules/security-oauth2/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  appserver/web/weld-integration/faces-config.NavData
Labels: Action Required, v:Payara-5

#2635 Bugfix: listener not using the correct keystore
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLImpl.java
  nucleus/security/core/src/test/java/com/sun/enterprise/security/ssl/GlassfishSSLImplTest.java
Labels: CLA, community-contribution

#2680 PAYARA-2711 Compress on Rotation doesn't work for Payara Notification Logger
  nucleus/admin/template/src/main/resources/config/logging.properties
Labels: v:Payara-5

#2688 PAYARA-2716 remove references to ear files from --help
  appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandoptions.properties
Labels: v:Payara-5

#2689 PAYARA-2716 remove references to ear files from --help
  appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandoptions.properties
Labels: v:Payara-4

#2644 PAYARA-2691 fix ResourceValidator Class Loaders
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
  appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java
  appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java
Labels: payara bug, v:Payara-5

#2645 PAYARA-2691 resource validation context cl p4
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
  appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java
  appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java
Labels: payara bug, v:Payara-4
