Repository payara/Payara, pull requests merged in 2018-05, with the labels that each got.

#2701 PAYARA-2720 Added missing packages to embedded distributions
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
Labels: 3:DevInProgress, in development

#2679 PAYARA-2425 Fix for using multiple envrionment variable in a line
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JvmOptions.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/CreateJvmOptions.java
Labels: v:Payara-5

#2681 PAYARA-1864 Add Let's Encypt to default truststore
  nucleus/admin/template/src/main/resources/config/cacerts.jks
Labels: v:Payara-5

#2673 PAYARA-2041 Implement Dynamic Logging Configuration
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/SyslogHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
Labels: v:Payara-5

#2686 PAYARA-2568 Add threaded system property to ensure multithreaded boot…
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/payara-boot.properties
Labels: v:Payara-5

#2687 PAYARA-2568 Add threaded system property to ensure multithreaded boot…
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/payara-boot.properties
Labels: v:Payara-4

#2736 PAYARA-2743 Deplopying an application to Deployment Group and the instances present in it, causes an error
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/CreateApplicationRefCommand.java
Labels: v:Payara-5

#2705 PAYARA-2549 - MicroProfile REST client v1.1
  appserver/extras/arquillian-containers/payara-client-ee7/pom.xml
  appserver/extras/arquillian-containers/payara-client-ee8/pom.xml
  appserver/extras/arquillian-containers/payara-micro/pom.xml
  appserver/extras/arquillian-containers/payara-remote/pom.xml
  appserver/extras/arquillian-containers/pom.xml
  appserver/packager/jersey/pom.xml
  appserver/packager/microprofile-package/pom.xml
  appserver/payara-appserver-modules/microprofile/pom.xml
  appserver/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress

#2719 PAYARA-2735 correct typo maintenance PR
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
Labels: v:Payara-4

#2648 Code coverage analysis using Jacoco
  nucleus/pom.xml
Labels: CLA, c:Enhancement, community-contribution, in review

#2721 PAYARA-2701 It is not possible to target a JDBC resource to a deployment group
  appserver/admingui/common/src/main/java/fish/payara/admingui/common/handlers/PayaraApplicationHandlers.java
  appserver/admingui/common/src/main/resources/resourceNode/resourceManageTargets.jsf
  appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java
  appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/CreateJdbcResource.java
  appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/DeleteJdbcResource.java
  nucleus/admin/util/src/main/java/org/glassfish/admin/cli/resources/CreateResourceRef.java
Labels: v:Payara-5

#2707 PAYARA-2608 Excessive use of JDBC connections for listing JBatch job executions
  appserver/admingui/full/src/main/resources/batch/batchJobs_1.inc
Labels: v:Payara-4

#2750 PAYARA-2730 NPE encountered when enabling Monitoring for HTTP Service
  appserver/web/admin/src/main/java/org/glassfish/web/admin/monitor/HttpServiceStatsProvider.java
Labels: v:Payara-4

#2744 PAYARA-2729 When listing batch job executions using "--long" options, it causes creation of excessive JDBC connections
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobs.java
Labels: v:Payara-4

#2666 PAYARA-223 hazelcast eclipselink cache coordination
  appserver/extras/payara-micro/payara-micro-distribution/pom.xml
  appserver/packager/glassfish-jpa/pom.xml
  appserver/payara-appserver-modules/hazelcast-eclipselink-coordination/pom.xml
  appserver/payara-appserver-modules/hazelcast-eclipselink-coordination/src/main/java/fish/payara/persistence/eclipselink/cache/coordination/HazelcastPayload.java
  appserver/payara-appserver-modules/hazelcast-eclipselink-coordination/src/main/java/fish/payara/persistence/eclipselink/cache/coordination/HazelcastPublishingTransportManager.java
  appserver/payara-appserver-modules/hazelcast-eclipselink-coordination/src/main/java/fish/payara/persistence/eclipselink/cache/coordination/HazelcastTopic.java
  appserver/payara-appserver-modules/hazelcast-eclipselink-coordination/src/main/java/fish/payara/persistence/eclipselink/cache/coordination/HazelcastTopicRemoteConnection.java
  appserver/payara-appserver-modules/hazelcast-eclipselink-coordination/src/main/java/fish/payara/persistence/eclipselink/cache/coordination/HazelcastTopicStorage.java
  appserver/payara-appserver-modules/hazelcast-eclipselink-coordination/src/main/java/fish/payara/persistence/eclipselink/cache/coordination/ReceiverMapping.java
  appserver/payara-appserver-modules/pom.xml
Labels: 3:DevInProgress, CLA, c:Enhancement, community-contribution, v:Payara-5

#2760 PAYARA-2730 NPE encountered when enabling Monitoring for HTTP Service
  appserver/web/admin/src/main/java/org/glassfish/web/admin/monitor/HttpServiceStatsProvider.java
Labels: v:Payara-5

#2753 PAYARA-2715 Error when configuring availability service in admin console
  appserver/admin/gf_template/src/main/resources/config/domain.xml
  appserver/admin/gf_template_web/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
  appserver/admingui/web/src/main/resources/configuration/webAvailabilityService.jsf
  appserver/admingui/web/src/main/resources/org/glassfish/web/admingui/Strings.properties
Labels: v:Payara-5

#2771 PAYARA-2714 Add links to the Availability Service page in Admin Console
  appserver/admingui/cluster/src/main/resources/availability/availabilityLink.jsf
  appserver/admingui/cluster/src/main/resources/availability/pluginTreeNodeAvailSvc.jsf
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_de.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_es.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_fr.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_it.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_ja.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_ko.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_pt_BR.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_zh_CN.properties
  appserver/admingui/ejb-lite-l10n/src/main/resources/org/glassfish/ejb-lite/admingui/Strings_zh_TW.properties
  appserver/admingui/ejb-lite/src/main/resources/org/glassfish/ejb-lite/admingui/Strings.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_de.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_es.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_fr.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_it.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_ja.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_ko.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_pt_BR.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_zh_CN.properties
  appserver/admingui/payara-console-extras-l10n/src/main/resources/fish/payara/admingui/extras/Strings_zh_TW.properties
  appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties
Labels: v:Payara-5

#2774 PAYARA-2767-Remove-Java8-Optional-reference
  appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/GetHttpListener.java
Labels: 3:DevInProgress, in development

#2773 PAYARA-2766-Remove-Java8-Collector-reference
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyService.java
Labels: 3:DevInProgress, in development

#2738 PAYARA-2747 Add options to add or remove mutiple instance from a Deployment Group
  nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/AddInstanceToDeploymentGroupCommand.java
  nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/ListDeploymentGroupsCommand.java
  nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/RemoveInstanceFromDeploymentGroupCommand.java
Labels: v:Payara-5

#2758 PAYARA-2041 Implement Dynamic Logging Configuration
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/SyslogHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
Labels: v:Payara-4

#2781 PAYARA-2769 Bundle patched(mp-rest-client) jersey for JDK8 Profile (Payara 4.x)
  appserver/extras/arquillian-containers/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress, in development

#2783 PAYARA-2765 Fix typo
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/admin/SetFaultToleranceConfigurationCommand.java
Labels: 3:DevInProgress, in development

#2754 PAYARA-2737 JDBC Resources have an incorrect number of targets
  appserver/admingui/common/src/main/java/fish/payara/admingui/common/handlers/PayaraApplicationHandlers.java
  appserver/admingui/common/src/main/resources/resourceNode/resourceEditTargets.jsf
  appserver/admingui/common/src/main/resources/resourceNode/resourceHandlers.inc
  appserver/admingui/common/src/main/resources/resourceNode/resourceManageTargets.jsf
Labels: v:Payara-5

#2786 PAYARA-2772 Application targets page doesn't display targets
  appserver/admingui/common/src/main/java/fish/payara/admingui/common/handlers/PayaraApplicationHandlers.java
Labels: v:Payara-5

#2702 PAYARA-2575 Yubikey Integration
  .gitignore
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/featuresets/payara-web/pom.xml
  appserver/featuresets/payara/pom.xml
  appserver/packager/external/pom.xml
  appserver/packager/glassfish-web/pom.xml
  appserver/packager/pom.xml
  appserver/packager/yubikey-authentication/pom.xml
  appserver/packager/yubikey-authentication/src/main/assembly/yubikey-authentication.xml
  appserver/packager/yubikey-authentication/src/main/resources/pkg_proto.py
  appserver/payara-appserver-modules/pom.xml
  appserver/payara-appserver-modules/yubikey-authentication/pom.xml
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/annotations/TwoIdentityStoreAuthenticationMechanismDefinition.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/annotations/YubikeyIdentityStoreDefinition.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/authentication/twoIdentityStore/CDIExtension.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/authentication/twoIdentityStore/TwoIdentityStoreAuthenticationMechanism.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/authentication/twoIdentityStore/TwoIdentityStoreAuthenticationMechanismState.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/identitystores/ConfigRetriever.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/identitystores/YubicoAPI.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/identitystores/YubicoAPIImpl.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/identitystores/YubikeyCredential.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/identitystores/YubikeyIdentityStore.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/identitystores/YubikeyIdentityStoreDefinitionAnnotationLiteral.java
  appserver/payara-appserver-modules/yubikey-authentication/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  appserver/pom.xml
Labels: 3:DevInProgress, DO NOT MERGE, in development

#2792 PAYARA-2592 Back Updated EclipseLink out of JDK7 Build
  appserver/pom.xml
Labels: 3:DevInProgress, in development

#2797 PAYARA-2780-Update-Weld-to-2.4.7.Final
  appserver/pom.xml
Labels: 3:DevInProgress, in development
