Repository payara/Payara, pull requests merged in 2018-07, with the labels that each got.

#2940 PAYARA-2894 OpenAPI Picks up Internal Applications
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
Labels: v:Payara-5

#2944 PAYARA-2875 SSL certificate has expired in Payara Micro - Payara4
  nucleus/admin/template/src/main/resources/config/keystore.jks
Labels: v:Payara-4

#2943 PAYARA-2875 SSL certificate has expired in Payara Micro
  nucleus/admin/template/src/main/resources/config/keystore.jks
Labels: v:Payara-5

#2931 #2930 typo
  appserver/admingui/cluster/src/main/resources/standalone/standaloneInstanceGeneral.jsf
  appserver/web/web-core/src/main/java/org/apache/catalina/LogFacade.java
Labels: CLA

#2941 PAYARA-2894 OpenAPI Picks up Internal Applications PAYARA4
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
Labels: v:Payara-4

#2972 PAYARA-2666 Show DeploymentException in Logs
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Labels: v:Payara-4

#2963 PAYARA-2910 RuntimeException in Admin Console JVM Options
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/InstanceHandler.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
Labels: v:Payara-5

#2968 PAYARA-2911 Can't set description for JMX Monitoring attributes
  appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/SetJMXMonitoringConfiguration.java
  nucleus/admin/rest/rest-service/src/main/java/fish/payara/admin/rest/resources/MonitoredAttributeBagResource.java
Labels: v:Payara-5

#2965 PAYARA-2871 Improve listing batch jobs memory usage in admin console
  appserver/admingui/full/src/main/java/fish/payara/full/admingui/handlers/BatchHandlers.java
  appserver/admingui/full/src/main/resources/batch/assets/js/batch.js
  appserver/admingui/full/src/main/resources/batch/assets/skins/payara_theme/batch-styles.css
  appserver/admingui/full/src/main/resources/batch/batchJobs_1.inc
  appserver/admingui/full/src/main/resources/batch/batchJobs_2.inc
  appserver/admingui/full/src/main/resources/batch/batchRequestParam.inc
  appserver/admingui/full/src/main/resources/org/glassfish/full/admingui/Strings.properties
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/AbstractListCommandProxy.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobs.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobsProxy.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/H2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java
Labels: v:Payara-5

#2995 PAYARA-2928 Update asm to version 5.0.4 (Payara 4)
  nucleus/pom.xml
Labels: v:Payara-4

#2990 PAYARA-2921 OpenTracing Swallows StackTraces PAYARA4
  appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingFilter.java
Labels: v:Payara-4

#3009 PAYARA-2953 Payara Micro Arquillian Container Doesn't Use Java Home
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: v:Payara-5

#2983 PAYARA-2929 Batch RuntimeConfiguration has wrong target
  appserver/admingui/full/src/main/resources/batch.jsf
  appserver/admingui/full/src/main/resources/batchConfigLink.jsf
  appserver/admingui/full/src/main/resources/pluginTreeNodeBatch.jsf
Labels: v:Payara-5
