Repository payara/Payara, pull requests merged in 2018-12, with the labels that each got.

#3446 PAYARA-3120 added EE contexts for CDI @TransactionScoped extension invocations
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedCDIUtil.java
Labels: v:Payara-5

#3436 Default Grizzly NPN Bootstrap Jar
  nucleus/packager/nucleus-grizzly/pom.xml
Labels: v:Payara-5

#3433 PAYARA-3265 Openapi using @Operation(hidden = true)
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/PathItemImpl.java
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/BaseProcessor.java
Labels: CLA, community-contribution

#3437 Logging: Replacing usage of Thread/Timer/TimerTask with PayaraExecuto…
  nucleus/core/logging/pom.xml
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogRotationTimer.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogRotationTimerTask.java
  nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/PayaraNotificationLogRotationTimer.java
  nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LogEventListenerTest.java
Labels: CLA, community-contribution

#3505 PAYARA-3258 Disabled Path Based Annotations For Interfaces
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java
Labels: v:Payara-5

#3503 PAYARA-3356 EJB Timer fails when using non-persistent flag with @Timeout (Payara 4.x)
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java
Labels: v:Payara-4

#3514 PAYARA-3362 Fix NPE in get-http-listener
  appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/GetHttpListener.java
Labels: v:Payara-5

#3515 PAYARA-3362 Fix NPE in get-http-listener
  appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/GetHttpListener.java
Labels: v:Payara-4

#3529 PAYARA-3366: Concurrency issue in retrieving MP Config Converter.
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
Labels: v:Payara-4

#3521 PAYARA-3358-asadmin-command-stop-domains-no-longer-works - Payara4
  nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/StopDomainsCommand.java
Labels: v:Payara-4

#3304 PAYARA-2636 Add TLS 1.3 Integration
  appserver/admingui/common/src/main/resources/shared/sslAttrs.inc
  appserver/admingui/common/src/main/resources/shared/sslPrepare.inc
  appserver/admingui/common/src/main/resources/shared/sslValidationsJS.inc
  appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
  appserver/appclient/client/acc-config/src/main/resources/configBindings.xml
  appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IIOPSSLSocketFactory.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/connector/coyote/PECoyoteConnector.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/security/integration/AppClientSSL.java
  nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ssl/SSLClientConfigurator.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Ssl.java
Labels: JDK-11+, v:Payara-5
