Repository payara/Payara, pull requests merged in 2018-08, with the labels that each got.

#2988 Fixed few of the Sonar issues
  appserver/admingui/common/src/main/java/fish/payara/admingui/common/handlers/PayaraApplicationHandlers.java
  appserver/admingui/full/src/main/java/fish/payara/full/admingui/handlers/BatchHandlers.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/BatchConstants.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobExecutions.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobExecutionsProxy.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobSteps.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobStepsProxy.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobs.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobsProxy.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/H2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
Labels: v:Payara-5

#3016 PAYARA-2921 Configurations tree view doesn't list in alphabetically order
  appserver/admingui/full/src/main/resources/META-INF/admingui/console-config.xml
  appserver/admingui/healthcheck-service-console-plugin/src/main/resources/META-INF/admingui/console-config.xml
  appserver/admingui/payara-console-extras/src/main/resources/META-INF/admingui/console-config.xml
Labels: v:Payara-5

#2727 PAYARA-1061 LetsEncrypt integration script
  appserver/packager/glassfish-common-web/src/main/resources/bin/letsencrypt.py
Labels: 4:Ready

#2964 PAYARA-2761 Create payara-web.xml functionality
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/io/DescriptorConstants.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/DOLUtils.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/DTDRegistry.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/RuntimeTagNames.java
  appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/payara-web-app_4.dtd
  appserver/web/gf-web-connector/src/main/java/org/glassfish/web/sniffer/WebSniffer.java
  appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
  appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/io/runtime/PayaraWebRuntimeDDFile.java
  appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/node/runtime/gf/PayaraWebBundleRuntimeNode.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericSniffer.java
  nucleus/deployment/common/src/main/java/com/sun/enterprise/deployment/deploy/shared/DeploymentPlanArchive.java
Labels: Action Required

#3044 PAYARA-3001 Cleaned Expired Certificates From cacerts.jks
  nucleus/admin/template/src/main/resources/config/cacerts.jks
  nucleus/grizzly/config/src/test/resources/cacerts.jks
  nucleus/security/core/src/main/resources/config/cacerts.jks
Labels: v:Payara-5

#3011 PAYARA-2288 Create a MicroProfile Settings Page into the Admin Console
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java
  appserver/admingui/microprofile-console-plugin/pom.xml
  appserver/admingui/microprofile-console-plugin/src/main/java/fish/payara/admingui/microprofile/MicroProfilePlugin.java
  appserver/admingui/microprofile-console-plugin/src/main/resources/META-INF/admingui/console-config.xml
  appserver/admingui/microprofile-console-plugin/src/main/resources/fish/payara/admingui/microprofile/Strings.properties
  appserver/admingui/microprofile-console-plugin/src/main/resources/images/microprofile.png
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/microprofileConfigAPITabs.inc
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/microprofileConfigLink.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/microprofileConfigTabs.inc
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/ordinalConfiguration.inc
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/propertyConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/secretsDirectoryConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/faultToleranceConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/healthCheckConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/metricsConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/openAPIConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/openTracingConfiguration.jsf
  appserver/admingui/microprofile-console-plugin/src/main/resources/pluginTreeNodeMicroprofile.jsf
  appserver/admingui/pom.xml
  appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ja.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ko.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_CN.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_TW.css
  appserver/packager/microprofile-package/pom.xml
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceServiceConfiguration.java
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/admin/SetFaultToleranceConfigurationCommand.java
  appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/admin/GetMPHealthCheckConfiguration.java
  appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/admin/SetMPHealthCheckConfiguration.java
  appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/config/MetricsHealthCheckConfiguration.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/GetMetricsConfigurationCommand.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/MetricsServiceConfiguration.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/SetMetricsConfigurationCommand.java
  appserver/pom.xml
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/GetConfigOrdinal.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/GetConfigSecretsDirectory.java
Labels: v:Payara-5

#3071 PAYARA-2929 Batch RuntimeConfiguration has wrong target - Payara4
  appserver/admingui/full/src/main/resources/batch.jsf
  appserver/admingui/full/src/main/resources/batchConfigLink.jsf
  appserver/admingui/full/src/main/resources/pluginTreeNodeBatch.jsf
Labels: v:Payara-4

#3067 PAYARA-3001 Remove Expired SSL Certificates PAYARA4
  nucleus/admin/template/src/main/resources/config/cacerts.jks
  nucleus/grizzly/config/src/test/resources/cacerts.jks
  nucleus/security/core/src/main/resources/config/cacerts.jks
Labels: v:Payara-4

#3066 PAYARA-2871 Improve listing batch jobs memory usage in admin console - Payara4
  appserver/admingui/full/src/main/java/fish/payara/full/admingui/handlers/BatchHandlers.java
  appserver/admingui/full/src/main/resources/batch/assets/js/batch.js
  appserver/admingui/full/src/main/resources/batch/assets/skins/payara_theme/batch-styles.css
  appserver/admingui/full/src/main/resources/batch/batchJobs_1.inc
  appserver/admingui/full/src/main/resources/batch/batchJobs_2.inc
  appserver/admingui/full/src/main/resources/batch/batchRequestParam.inc
  appserver/admingui/full/src/main/resources/org/glassfish/full/admingui/Strings.properties
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/AbstractListCommandProxy.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobs.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobsProxy.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/H2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java
Labels: v:Payara-4

#3070 PAYARA-2911 Can't set description for JMX Monitoring attributes - Payara4
  appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/SetMonitoringConfiguration.java
  nucleus/admin/rest/rest-service/src/main/java/fish/payara/admin/rest/resources/MonitoredAttributeBagResource.java
Labels: v:Payara-4

#3073 Fixed few of the Sonar issues - Payara4
  appserver/admingui/full/src/main/java/fish/payara/full/admingui/handlers/BatchHandlers.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/BatchConstants.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobExecutions.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobExecutionsProxy.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobSteps.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobStepsProxy.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobs.java
  appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobsProxy.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/H2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
Labels: v:Payara-4

#3069 PAYARA-2921 Configurations tree view doesn't list in alphabetically order - Payara4
  appserver/admingui/full/src/main/resources/META-INF/admingui/console-config.xml
  appserver/admingui/healthcheck-service-console-plugin/src/main/resources/META-INF/admingui/console-config.xml
  appserver/admingui/payara-console-extras/src/main/resources/META-INF/admingui/console-config.xml
Labels: v:Payara-4

#3075 PAYARA-3033 Disable Eclipse MicroProfile SNAPSHOT Downloads
  nucleus/pom.xml
Labels: v:Payara-5

#3074 PAYARA-2941 Updated Grizzly to 2.4.3.payara-p5.
  nucleus/pom.xml
Labels: v:Payara-5

#3041 PAYARA-2924 NPE on JAX-RS Async-Server EE7 Sample
  api/payara-api/src/main/java/fish/payara/notification/requesttracing/RequestTraceSpan.java
  appserver/concurrent/concurrent-impl/pom.xml
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/InvocationContext.java
  appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/JaxrsClientRequestTracingFilter.java
  appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingFilter.java
  appserver/web/web-core/pom.xml
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java
  nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingScope.java
  nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/ScopeManager.java
  nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/propagation/MapToTextMap.java
  nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/span/Span.java
  nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/tracer/Tracer.java
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java
Labels: Action Required

#3096 PAYARA-635 Interactive shell now has tab autocomplete
  nucleus/admin/cli/pom.xml
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java
  nucleus/osgi-platforms/osgi-cli-interactive/pom.xml
  nucleus/packager/nucleus/pom.xml
Labels: v:Payara-5

#3094 PAYARA-3038 Jersey JAXB Unmarshalling Error
  appserver/extras/arquillian-containers/payara-client-ee8/pom.xml
  appserver/extras/arquillian-containers/pom.xml
  nucleus/pom.xml
Labels: v:Payara-5
