Repository payara/Payara, pull requests merged in 2018-03, with the labels that each got.

#2492 PAYARA-2563 Fix tck failure in config api
  appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigProducer.java
Labels: 3:DevInProgress

#2491 PAYARA-2563 Fix tck failure in config api
  appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigProducer.java
Labels: 3:DevInProgress

#2493 PAYARA-2561 CORBA authentication leakage
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecServerRequestInterceptor.java
Labels: 4:Ready

#2494 PAYARA-2564 multi-threaded InitialContext() fix
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
Labels: 4:Ready

#2496 Updated links to javadoc and other links on payara.github.io
  index.html
Labels: 3:DevInProgress

#2489 PAYARA-2558 Embedded Contains Non-Optional Dependencies
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
Labels: 3:DevInProgress

#2497 PAYARA-2528-Payara-Micro-ignores-invalid-arguments-if-they-dont-startwith-double-dash
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RuntimeOptions.java
  appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandlogstrings.properties
Labels: 3:DevInProgress

#2495 PAYARA-2562-NPE-reported-when-setting-monitoring-levels-after-secure-admin-is-enabled
  appserver/web/admin/src/main/java/org/glassfish/web/admin/monitor/HttpServiceStatsProvider.java
Labels: 3:DevInProgress

#2498 Added more information on auto-closing of unresponsive issues
  .github/CONTRIBUTING.md
Labels: 3:DevInProgress

#2279 PAYARA-2267 JPA Conversion now unwraps connection properly
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/ConnectionHolder.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ConnectionHolder40.java
Labels: 3:DevInProgress, DO NOT MERGE

#2487 PAYARA-2189 filter class not found by applications in CDI events
  appserver/payara-appserver-modules/payara-jsr107/osgi.bundle
  appserver/payara-appserver-modules/payara-jsr107/pom.xml
  appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/implementation/PayaraValueHolder.java
  appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java
  appserver/web/gf-web-connector/osgi.bundle
  appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java
Labels: 4:Ready, v:Payara-5

#2504 Small amount of cleaning / refactoring of the EJB security module
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/AlternateSecurityInterceptorFactory.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/CSIV2TaggedComponentInfo.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/ConnectionContext.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/ConnectionExecutionContext.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecServerRequestInterceptor.java
Labels: 4:Ready

#2502 PAYARA-2466 Finally squash the unnecessary Felix warnings
  nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Labels: 3:DevInProgress

#2501 PAYARA-2522 Deploying an application to an Instance in a Deployment Group and the Deployment Group causes the application to only target the instance
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/CreateApplicationRefCommand.java
Labels: 3:DevInProgress

#2500 Small amount of cleaning / refactoring of in-mem jacc module
  appserver/security/inmemory.jacc.provider/src/main/java/com/sun/enterprise/security/jacc/provider/GlassfishRoleMapper.java
  appserver/security/inmemory.jacc.provider/src/main/java/com/sun/enterprise/security/jacc/provider/JACCRoleMapper.java
  appserver/security/inmemory.jacc.provider/src/main/java/com/sun/enterprise/security/jacc/provider/Role.java
  appserver/security/inmemory.jacc.provider/src/main/java/com/sun/enterprise/security/jacc/provider/SharedState.java
  appserver/security/inmemory.jacc.provider/src/main/java/com/sun/enterprise/security/jacc/provider/SimplePolicyConfiguration.java
  appserver/security/inmemory.jacc.provider/src/main/java/com/sun/enterprise/security/jacc/provider/SimplePolicyConfigurationFactory.java
  appserver/security/inmemory.jacc.provider/src/main/java/com/sun/enterprise/security/jacc/provider/SimplePolicyProvider.java
Labels: 3:DevInProgress

#2514 PAYARA-2466 Finally squash the unnecessary Felix warnings
  nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Labels: 3:DevInProgress

#2522 Revert "PAYARA-2265 enable ansi colours on all OSs"
  nucleus/core/logging/pom.xml
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColor.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColorFormatter.java
  nucleus/packager/nucleus/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress

#2512 PAYARA-2541 synch HK2 Dom class race condition
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TargetBasedResolver.java
  nucleus/admin/rest/rest-service/src/main/java/fish/payara/admin/rest/resources/MonitoredAttributeBagResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/LeafResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateListOfResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateRestResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/DomainXmlVerifier.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/DeleteSystemProperty.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/V2DottedNameSupport.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/NetworkListener.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/ThreadPool.java
Labels: 4:Ready

#2519 PAYARA-2566 Update to Soteria P3
  appserver/pom.xml
Labels: 3:DevInProgress

#2533 prevent startup failure when NPN is not on boot classpath and unable …
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java
Labels: 3:DevInProgress, v:Payara-5

#2554 PAYARA-2613 fix JSF warnings that fill up log files w/virtual servers - Payara 4
  appserver/web/web-glue/pom.xml
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
Labels: 4:Ready, upstream bug, v:Payara-4

#2553 PAYARA-2613 fix JSF warnings that fill up log files w/virtual servers
  appserver/web/web-glue/pom.xml
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
Labels: 4:Ready, upstream bug, v:Payara-5

#2555 PAYARA-2621 Corrected capitalisation in splash screen image.
  appserver/admingui/core/src/main/resources/images/backimage.jpg
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/adapter/backimage.jpg
Labels: in review

#2532 PAYARA-2579 Added keyfile to Payara Micro distribution
  appserver/extras/payara-micro/payara-micro-distribution/build.xml
Labels: 3:DevInProgress, v:Payara-4

#2507 PAYARA-2569 Undeploying from a deployment group no longer has instanc…
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/DeploymentHandler.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Domain.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UndeployCommand.java
Labels: 3:DevInProgress, v:Payara-5

#2510 PAYARA-2571 Viewing monitoring info in the admin console no longer th…
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/MonitoringHandlers.java
Labels: 3:DevInProgress, v:Payara-5

#2511 PAYARA-2570 asadmin start-database command implicit mapping to H2 dbtype
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DBType.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DatabaseCommand.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/LocalStrings.properties
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/StartDatabaseCommand.java
  appserver/tests/quicklook/QuickLook_Test_Instructions.html
  appserver/tests/quicklook/gfproject/db-targets.xml
Labels: 3:DevInProgress, v:Payara-5

#2518 PAYARA-2229 fixed CDI extension injection regression with EAR files for Payara 5
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java
  appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Labels: 4:Ready, v:Payara-5

#2528 PAYARA-2461 Options to allow the application's name to be used for Portable JNDI name of EJBs contained within an EAR
  appserver/admingui/full/src/main/resources/apps/deploymentAppClient.jsf
  appserver/admingui/full/src/main/resources/apps/deploymentEar.jsf
  appserver/admingui/full/src/main/resources/apps/deploymentEarFields.jsf
  appserver/admingui/jca/src/main/resources/apps/deploymentRar.jsf
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
Labels: 3:DevInProgress, v:Payara-5

#2531 PAYARA-2558 Embedded Contains Non Optional Dependencies
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
Labels: 3:DevInProgress, v:Payara-4

#2530 PAYARA-2425 Added Environment substitution for JVM options
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JvmOptions.java
Labels: 3:DevInProgress, v:Payara-4

#2517 PAYARA-2229 fixed CDI extension injection regression with EAR files
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java
  appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Labels: 4:Ready, v:Payara-4

#2544 PAYARA-2590 Fixes #2521 Payara Micro now correctly reports https port…
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/PayaraServerProperties.java
Labels: 3:DevInProgress, v:Payara-4

#2557 PAYARA-2579 Added keyfile to Payara Micro distribution
  appserver/extras/payara-micro/payara-micro-distribution/build.xml
Labels: 3:DevInProgress, in development

#2546 PAYARA-2615 Add support for Payara Micro command line option --sslCert
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishServerSocketFactory.java
  nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
Labels: v:Payara-4

#2549 PAYARA-2614 Add Missing HTTP/2 Configuration Options
  appserver/admingui/common/src/main/resources/org/glassfish/common/FieldLengths.properties
  appserver/admingui/web/src/main/resources/grizzly/http.layout
  appserver/admingui/web/src/main/resources/grizzly/httpAttr.inc
  appserver/admingui/web/src/main/resources/org/glassfish/web/admingui/Strings.properties
  appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/CreateHttp.java
  appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/CreateHttpListener.java
  appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/GetProtocol.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Http.java
Labels: 3:DevInProgress

#2556 PAYARA-2620 Fix Application Edit Post Request
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java
Labels: in development

#2548 PAYARA-2612 removed underscore from field names in JSON Formatter
  nucleus/admin/template/src/main/resources/config/logging.properties
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
  nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
Labels: 3:DevInProgress

#2545 PAYARA-2615 Add support for Payara Micro command line option --sslCert
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishServerSocketFactory.java
  nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
Labels: 3:DevInProgress, v:Payara-5

#2543 PAYARA-2590 Fixes #2521 Payara Micro now correctly reports https port…
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/PayaraServerProperties.java
Labels: 3:DevInProgress, v:Payara-5

#2561 PAYARA-2623 Grizzly patch version 2.4.3.payara-p1 upgrade
  nucleus/grizzly/config/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress, in development

#2565 PAYARA-2630 Fix exception during boot when Payara started via java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/FileMonitoringImpl.java
Labels: 3:DevInProgress, in development

#2563 PAYARA-2546 Update Metrics to 1.1
  appserver/payara-appserver-modules/microprofile/metrics/pom.xml
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/MetricRegistryImpl.java
  appserver/pom.xml
Labels: in development

#2547 PAYARA-2616-Align-javaee-api-dependency-versions-to-8.0
  api/pom.xml
  appserver/extras/arquillian-containers/payara-common/dependency-reduced-pom.xml
  appserver/extras/arquillian-containers/payara-common/pom.xml
  appserver/extras/arquillian-containers/payara-managed/pom.xml
  appserver/extras/arquillian-containers/payara-micro/pom.xml
  appserver/extras/arquillian-containers/payara-remote/pom.xml
  appserver/extras/arquillian-containers/pom.xml
  appserver/extras/payara-micro/payara-micro-boot/pom.xml
  appserver/payara-appserver-modules/cdi-auth-roles/pom.xml
  appserver/payara-appserver-modules/hazelcast-ejb-timer/pom.xml
  appserver/payara-appserver-modules/jaspic-servlet-utils/pom.xml
  appserver/payara-appserver-modules/microprofile/fault-tolerance/pom.xml
  appserver/payara-appserver-modules/microprofile/healthcheck/pom.xml
  appserver/payara-appserver-modules/microprofile/jwt-auth/pom.xml
  appserver/payara-appserver-modules/microprofile/metrics/pom.xml
  appserver/payara-appserver-modules/notification-datadog-core/pom.xml
  appserver/payara-appserver-modules/notification-email-core/pom.xml
  appserver/payara-appserver-modules/notification-hipchat-core/pom.xml
  appserver/payara-appserver-modules/notification-jms-core/pom.xml
  appserver/payara-appserver-modules/notification-newrelic-core/pom.xml
  appserver/payara-appserver-modules/notification-slack-core/pom.xml
  appserver/payara-appserver-modules/notification-xmpp-core/pom.xml
  appserver/payara-appserver-modules/payara-jsr107/pom.xml
  appserver/payara-appserver-modules/payara-micro-cdi/pom.xml
  appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-service/pom.xml
  nucleus/payara-modules/notification-cdi-eventbus-core/pom.xml
  nucleus/payara-modules/notification-core/pom.xml
  nucleus/payara-modules/notification-eventbus-core/pom.xml
  nucleus/payara-modules/requesttracing-core/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress

#2570 PAYARA-2566 Update to Soteria P3 (#2519)
  appserver/pom.xml
Labels: 3:DevInProgress, in development

#2568 PAYARA-2546 Update Metrics to 1.1 (Payara4)
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/MetricRegistryImpl.java
  appserver/pom.xml
Labels: 3:DevInProgress, in development

#2520 PAYARA-2582 …
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
Labels: 3:DevInProgress, Action Required, v:Payara-5

#2577 PAYARA-2582 … (#2520)
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
Labels: 3:DevInProgress, in development

#2576 PAYARA-2619-Add-a-version-number-to-Maven-build-plugin
  appserver/admingui/devtests/pom.xml
  appserver/extras/arquillian-containers/payara-managed/pom.xml
  appserver/extras/arquillian-containers/payara-remote/pom.xml
  appserver/extras/arquillian-containers/pom.xml
  appserver/tests/cdi/cases/runner/pom.xml
  appserver/tests/cdi/negative/runner/pom.xml
  appserver/tests/embedded/basic/lifecycle/pom.xml
  appserver/tests/embedded/cdi_basic/pom.xml
  appserver/tests/embedded/cdi_ejb_jpa/pom.xml
  appserver/tests/embedded/glassfish_resources_xml/pom.xml
  appserver/tests/embedded/inplanted/pom.xml
  appserver/tests/embedded/maven-plugin/pom.xml
  appserver/tests/embedded/scatteredarchive/pom.xml
  appserver/tests/embedded/static/web/pom.xml
  appserver/tests/embedded/web/web-all/pom.xml
  appserver/tests/embedded/web/web-api/pom.xml
  appserver/tests/embedded/web/web-war/test/pom.xml
  appserver/tests/hk2/cdi/basic/runner/pom.xml
  appserver/tests/hk2/cdi/ear/runner/pom.xml
  appserver/tests/hk2/cdi/jersey/runner/pom.xml
  appserver/tests/hk2/cdi/jersey/war/pom.xml
  appserver/tests/hk2/isolation/runner/pom.xml
  nucleus/payara-modules/nucleus-microprofile/config-service/pom.xml
  nucleus/pom.xml
  nucleus/tests/admin/pom.xml
Labels: 3:DevInProgress, in development

#2572 Update Arquillian Container Versions
  appserver/extras/arquillian-containers/payara-client-ee7/pom.xml
  appserver/extras/arquillian-containers/payara-client-ee8/pom.xml
  appserver/extras/arquillian-containers/payara-common/dependency-reduced-pom.xml
  appserver/extras/arquillian-containers/payara-common/pom.xml
  appserver/extras/arquillian-containers/payara-embedded/pom.xml
  appserver/extras/arquillian-containers/payara-managed/pom.xml
  appserver/extras/arquillian-containers/payara-micro/pom.xml
  appserver/extras/arquillian-containers/payara-remote/pom.xml
  appserver/extras/arquillian-containers/pom.xml
Labels: 3:DevInProgress, in development

#2579 New Payara 5 Admin Console design doesn't display on Japanese, Korean and Chinese language.
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ja.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ko.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_CN.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_TW.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/commontaskssection_ja.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/commontaskssection_ko.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/commontaskssection_zh_CN.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/commontaskssection_zh_TW.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_ja.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_ko.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_zh_CN.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_zh_TW.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/typography_ja.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/typography_ko.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/typography_zh_CN.css
  appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/typography_zh_TW.css
Labels: in development, v:Payara-5

#2574 PAYARA-2425 Added Environment substitution for JVM options
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JvmOptions.java
Labels: 3:DevInProgress, in development

#2584 PAYARA-2628-Payara-Micro-copytouberjar-duplicates-the-name-of-the-directory
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
Labels: 3:DevInProgress, in development

#2586 PAYARA-2628-Payara-Micro-copytouberjar-duplicates-the-name-of-the-directory-Payara-4
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
Labels: 3:DevInProgress, in development

#2583 PAYARA-2461 Options to allow the application's name to be used for Portable JNDI name of EJBs contained within an EAR
  appserver/admingui/full/src/main/resources/apps/deploymentAppClient.jsf
  appserver/admingui/full/src/main/resources/apps/deploymentEar.jsf
  appserver/admingui/full/src/main/resources/apps/deploymentEarFields.jsf
  appserver/admingui/jca/src/main/resources/apps/deploymentRar.jsf
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
Labels: in development

#2582 PAYARA-2310 back port of changes done in PAYARA-1305
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Labels: 3:DevInProgress, in development

#2575 PAYARA-2349 Improved data format of SQL tracing data (#2559)
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/MonitoringHandlers.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/GuiUtil.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/monitoring/JdbcStatsProvider.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/stats/FrequentSQLTraceCache.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/stats/SlowSqlTraceCache.java
  nucleus/pom.xml
Labels: in development

#2539 Implement SNI support for both Micro and Server PAYARA-1528
  appserver/admingui/common/src/main/resources/shared/sslAttrs.inc
  appserver/admingui/common/src/main/resources/shared/sslPrepare.inc
  appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  nucleus/admin/template/src/main/resources/config/keystore.jks
  nucleus/grizzly/config/pom.xml
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Ssl.java
  nucleus/grizzly/nucleus-grizzly-all/pom.xml
Labels: 3:DevInProgress, v:Payara-5

#2540 PAYARA-1528 implement SNI support for Payara Server and Payara Micro
  appserver/admingui/common/src/main/resources/shared/sslAttrs.inc
  appserver/admingui/common/src/main/resources/shared/sslPrepare.inc
  appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  nucleus/admin/template/src/main/resources/config/keystore.jks
  nucleus/grizzly/config/pom.xml
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Ssl.java
  nucleus/grizzly/nucleus-grizzly-all/pom.xml
Labels: 3:DevInProgress, v:Payara-4
