Repository payara/Payara, pull requests merged in 2018-06, with the labels that each got.

#2812 PAYARA-2789 String Array Config API Injection Fails
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/StringArrayConverter.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
Labels: 3:DevInProgress, in development

#2823 PAYARA-2826 Exception is no longer thrown in AMXJ2EEStartupService wh…
  appserver/common/amx-javaee/src/main/java/org/glassfish/admin/amx/impl/j2ee/loader/AMXJ2EEStartupService.java
Labels: v:Payara-5

#2804 PAYARA-2745 Downport PAYARA-2744 Bulk Read for REST monitoring - Payara4
  appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/src/main/java/fish/payara/monitoring/rest/app/MBeanServerDelegate.java
  appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/src/main/java/fish/payara/monitoring/rest/app/RestMonitoringAppConfig.java
  appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/src/main/java/fish/payara/monitoring/rest/app/handler/MBeanAttributesReadHandler.java
  appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/src/main/java/fish/payara/monitoring/rest/app/resource/MBeanBulkReadResource.java
Labels: 3:DevInProgress, in development, v:Payara-4

#2810 PAYARA-2518 Jersey patch upgrade v2.27.payara-p6
  appserver/extras/arquillian-containers/payara-client-ee8/pom.xml
  appserver/extras/arquillian-containers/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress, in development, v:Payara-5

#2813 PAYARA-2788 Changing port now works for an non-admin http listener fo…
  appserver/web/admin/src/main/java/fish/payara/grizzly/config/admin/cli/SetNetworkListenerConfiguration.java
Labels: v:Payara-5

#2824 PAYARA-2822 Access logs are not beeing purged
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
Labels: v:Payara-5

#2840 PAYARA-2848 catch ConcurrentModificationException
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UndeployCommand.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/util/CleanupPostBoot.java
Labels: CLA, community-contribution

#2848 PAYARA-2828 Add rotation on file fize options on Access logging
  appserver/admingui/web/src/main/resources/configuration/accessLog.jsf
  appserver/admingui/web/src/main/resources/org/glassfish/web/admingui/Strings.properties
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/AccessLog.java
Labels: v:Payara-5

#2845 PAYARA-2843 Add Logging format options to Payara Notification Logger
  appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf
  appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties
  nucleus/admin/template/src/main/resources/config/logging.properties
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/Constants.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingPropertyNames.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
Labels: v:Payara-5

#2820 PAYARA-2824 Fixes in CDI event notif.
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
  appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java
Labels: v:Payara-5

#2811 PAYARA-2787 Resolved maven warnings on start build
  appserver/pom.xml
  nucleus/packager/nucleus-hk2/pom.xml
  nucleus/packager/nucleus-jersey/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress, in development

#2861 PAYARA-2788 Changing port now works for an non-admin http listener - Payara4
  appserver/web/admin/src/main/java/fish/payara/grizzly/config/admin/cli/SetNetworkListenerConfiguration.java
Labels: v:Payara-4

#2859 PAYARA-2822 - Payara4
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
Labels: v:Payara-4

#2879 PAYARA-2828 - Add rotation on file fize options on Access logging Payara4
  appserver/admingui/web/src/main/resources/configuration/accessLog.jsf
  appserver/admingui/web/src/main/resources/org/glassfish/web/admingui/Strings.properties
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/AccessLog.java
Labels: v:Payara-4

#2878 PAYARA-2843 - Add Logging format options to Payara Notification Logger Payara4
  appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf
  appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties
  nucleus/admin/template/src/main/resources/config/logging.properties
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/Constants.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingPropertyNames.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
Labels: v:Payara-4

#2889 PAYARA-2850 Readme.txt is incorrect in the 5.x distribution
  appserver/packager/appserver-base/src/main/docs/README.txt
Labels: v:Payara-5

#2906 Fixed a typo in Readme file
  appserver/packager/appserver-base/src/main/docs/README.txt
Labels: v:Payara-5

#2905 Corrected the Readme.txt to match the latest Payara release - Payara4
  appserver/packager/appserver-base/src/main/docs/README.txt
Labels: v:Payara-4

#2896 #2674 fixing several resource handling misses
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java
  appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java
  appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/util/NamingUtilsImpl.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroLauncher.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/ExplodedURLClassloader.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/Launcher.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/jar/JarFile.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/RuntimeDirectory.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
  appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/Main.java
  appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/DatabaseOutputStream.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/DelegatedRecoveryManager.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java
  appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardSession.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusEventJsonProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusJsonProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonHashMapProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonParameterMapProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelListReader.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelReader.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/ProgressStatusEventJsonProprietaryReader.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ValidateDcom.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/net/NetUtils.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/Syslog.java
Labels: CLA

#2911 PAYARA-2635 HTTP 500 error is thrown when trying to sort instances using node.
  appserver/admingui/cluster/src/main/resources/shared/instancesTable.inc
Labels: v:Payara-5
