Repository payara/Payara, pull requests merged in 2018-02, with the labels that each got.

#2382 PAYARA-2436 Removed Redundant Payara Fang Module
  appserver/packager/payara-fang/pom.xml
  appserver/payara-appserver-modules/payara-fang/payara-fang-service/pom.xml
  appserver/payara-appserver-modules/payara-fang/payara-fang-war/pom.xml
  appserver/payara-appserver-modules/payara-fang/pom.xml
Labels: 3:DevInProgress

#2385 PAYARA-2038 Remove Payara Micro Non-Optional Dependencies
  appserver/extras/payara-micro/payara-micro-distribution/pom.xml
Labels: 3:DevInProgress

#2377 PAYARA-2378 JSON Parsing issues
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/model/SseResponseBody.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/AdminCommandStateCmdResultJsonProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/AdminCommandStateJsonProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/OptionsResultJsonProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonParameterMapProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/JsonUtil.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/AdminCommandStateJsonProprietaryReader.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/ProgressStatusDTOJsonProprietaryReader.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/ProgressStatusEventJsonProprietaryReader.java
Labels: 3:DevInProgress

#2379 PAYARA-2212 Fix Weld warning for asynccontext used in other http thread
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
Labels: 3:DevInProgress

#2391 PAYARA-2494 merge master into Payara 5
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContextImpl.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/extras/payara-micro/payara-micro-distribution/pom.xml
  appserver/jms/gf-jms-injection/src/main/java/org/glassfish/jms/injection/InjectableJMSContext.java
  appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigPropertyProducer.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
Labels: 3:DevInProgress

#2389 PAYARA-2435 Fix Payara Embedded
  appserver/payara-appserver-modules/payara-micro-service/pom.xml
  appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstanceImpl.java
  appserver/web/gf-web-connector/pom.xml
  appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java
  appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/DomainDiscoveryService.java
Labels: 3:DevInProgress

#2333 PAYARA-2396 Set properties via admin console now works
  appserver/admingui/common/pom.xml
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/gadget/GadgetHandlers.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/JSONUtil.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestResponse.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
  nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java
  nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/Util.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/RestAdapter.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonHashMapProvider.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/JsonUtil.java
Labels: 3:DevInProgress

#2376 PAYARA-2335 UX Issue on Data Grid Admin console
  appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcast.js
  appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcast.jsf
Labels: 3:DevInProgress

#2388 PAYARA-2427 Payara Micro Deployed Application Produces Log Spam
  appserver/extras/payara-micro/payara-micro-boot/pom.xml
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/data/InstanceDescriptor.java
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/data/ModuleDescriptor.java
  appserver/extras/payara-micro/payara-micro-core/pom.xml
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandoptions.properties
  appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptorImpl.java
Labels: 3:DevInProgress

#2180 Update FileDirContext.java
  appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java
Labels: CLA, DO NOT MERGE

#2396 PAYARA-2503 Updated Weld from 3.0.2 to 3.0.3
  appserver/pom.xml
Labels: 3:DevInProgress

#2393 PAYARA-2502 Requesttraces now use correct endtime
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTrace.java
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTraceStoreCleanupTask.java
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/ListRequestTraces.java
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/domain/RequestTraceSpan.java
Labels: 3:DevInProgress

#2397 PAYARA-2468 Updated Mojarra to P7 to prevent junk logging
  appserver/pom.xml
Labels: 3:DevInProgress

#2354 PAYARA-2442 H2 jdbc-connection-pool config
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/H2Control.java
  appserver/admin/gf_template/src/main/resources/config/domain.xml
  appserver/admin/gf_template_web/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
  appserver/tests/embedded/web/web-api/src/main/resources/org/glassfish/tests/webapi/domain.xml
  appserver/tests/quicklook/ejb/cmp/metadata/sun-ejb-jar.xml
  nucleus/admin/launcher/src/test/resources/domains/baddomain/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domain1/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domain2/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domain3/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domainNoLog/config/domain.xml
  nucleus/core/kernel/src/main/resources/org/glassfish/embed/domain.xml
Labels: 3:DevInProgress

#2399 PAYARA-2406 Add Clustering Switch To Micro Arquillian Container
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2398 PAYARA-2505 clusterrequetstracestore can now remove traces
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/store/ClusteredRequestTraceStore.java
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/store/strategy/ReservoirTraceStorageStrategy.java
Labels: 3:DevInProgress

#2404 PAYARA-2429 Changed default start port
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
Labels: 3:DevInProgress

#2406 PAYARA-2500 Update Micro Arquillian Container For New Instance Descriptor Format
  appserver/extras/arquillian-containers/payara-common/pom.xml
  appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/PayaraVersion.java
  appserver/extras/arquillian-containers/payara-common/src/test/java/fish/payara/arquillian/container/payara/PayaraVersionTest.java
  appserver/extras/arquillian-containers/payara-micro/pom.xml
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2401 PAYARA-2507 Eventbus listeners no longer registered twice
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/eventbus/EventBus.java
Labels: 3:DevInProgress

#2407 PAYARA-2364 PAYARA-2412 Updated to Soteria P2 fixing exception and log
  appserver/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress

#2408 PAYARA-2510 Upgrade Soteria in 4.x to fix bugs
  appserver/pom.xml
Labels: 3:DevInProgress

#2411 Micro arquillian autobindhttp
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2412 Added configurable property to disable --autoBindHttp
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2410 PAYARA-2514 Escape quotes in request traces spans properly
  nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/domain/RequestTraceSpan.java
Labels: 3:DevInProgress

#2413 PAYARA-2516 Fixed JWT failure by correcting packager pom
  appserver/extras/payara-micro/payara-micro-distribution/pom.xml
  appserver/packager/microprofile-package/pom.xml
Labels: 3:DevInProgress

#2416 PAYARA-2506 Upgrade Hazecast to 3.9.3 and JCache to 1.1 for 4.x
  nucleus/payara-modules/jsr107-repackaged/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress

#2409 PAYARA-2504 allowLinking set to false
  appserver/web/web-core/src/main/resources/org/apache/catalina/core/mbeans-descriptors.xml
Labels: 3:DevInProgress

#2417 PAYARA-2517 Updated JBatch to P3 with Weld logging fix
  appserver/pom.xml
Labels: 3:DevInProgress

#2415 PAYARA-2506 upgrade Hazelcast and JCache API for 5.x
  nucleus/payara-modules/jsr107-repackaged/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress

#2420 PAYARA-2511 Ensure Optional property is returned as empty and not as unconfigured value
  appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigProducer.java
Labels: 3:DevInProgress

#2418 PAYARA-2512 Ensure formatter added to handler correctly on reading log config
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java
  nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
Labels: 3:DevInProgress

#2421 PAYARA-2518 Update 3 individual jars to Jersey 2.26 p1
  appserver/packager/jersey/pom.xml
Labels: 3:DevInProgress

#2422 Update Readme
  appserver/packager/appserver-base/src/main/docs/README.txt
Labels: 3:DevInProgress

#2419 Upgrade to patched grizzly ALPN for JDK8u161 and above
  nucleus/pom.xml
Labels: 3:DevInProgress

#2429 PAYARA-2365 Remove Redundant Rest Endpoint Info
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java
  appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java
  appserver/admingui/payara-console-extras/src/main/resources/payaraRestEndpoints/payaraRestEndpoints.jsf
  appserver/extras/payara-micro/payara-micro-core/pom.xml
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java
Labels: 3:DevInProgress

#2428 PAYARA-2370 Move Arquillian extension into TCK runner project
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/README.adoc
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/pom.xml
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/java/fish/payara/microprofile/jwtauth/tck/ArquillianArchiveProcessor.java
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/java/fish/payara/microprofile/jwtauth/tck/ArquillianExtension.java
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/java/fish/payara/microprofile/jwtauth/tck/TokenParser.java
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/java/fish/payara/microprofile/jwtauth/tck/URLResourceProvider.java
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/resources/META-INF/services/org.eclipse.microprofile.jwt.tck.util.ITokenParser
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/resources/payara-mp-jwt.properties
  appserver/payara-appserver-modules/microprofile/jwt-auth-tck/src/main/resources/web.xml
Labels: 3:DevInProgress

#2434 PAYARA-2524-Duplicate-Jackson-jar-packaged-into-Payara-Micro
  appserver/extras/payara-micro/payara-micro-distribution/pom.xml
Labels: 3:DevInProgress

#2435 PAYARA-2474 changed logger for ConcurrentObjectFactory
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ConcurrentObjectFactory.java
Labels: 3:DevInProgress

#2443 PAYARA-2389 Fix log message and add duration
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/RetryInterceptor.java
Labels: 3:DevInProgress

#2442 PAYARA-2530 Payara Micro Fails To Produce Instance Descriptor
  appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptorImpl.java
Labels: 3:DevInProgress

#2445 PAYARA-2531 Fixes #2430
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
Labels: 3:DevInProgress

#2439 PAYARA-2529-Align-JMS-Api-versions-by-using-maven-property
  appserver/extras/payara-micro/payara-micro-distribution/pom.xml
  appserver/tests/embedded/maven-plugin/pom.xml
  appserver/tests/paas/mq-shared-service-test/mq-app/ejb/pom.xml
  appserver/tests/paas/mq-shared-service-test/mq-app/web/pom.xml
Labels: 3:DevInProgress

#2444 PAYARA-2515 Micro Arquillian Tests Fail In Parallel
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PortBinder.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyProxy.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyService.java
  nucleus/core/kernel/src/main/java/fish/payara/kernel/services/impl/MicroNetworkListener.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java
Labels: 3:DevInProgress

#2424 PAYARA-2440 Refactor Pretty Date Format
  appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/PayaraUtilHandlers.java
Labels: 3:DevInProgress

#2446 PAYARA-2326 Added switch in glassfish-web to switch JAX-RS @RolesAllowed
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/Application.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/WebBundleDescriptor.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/RuntimeTagNames.java
  appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-web-app_3_0-1.dtd
  appserver/payara-appserver-modules/microprofile/jwt-auth/pom.xml
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jaxrs/RolesAllowedAutoDiscoverable.java
  appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java
  appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/node/runtime/gf/WebBundleRuntimeNode.java
Labels: 3:DevInProgress

#2432 PAYARA-2525 Don't scan all classes when not needed.
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldApplicationContainer.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/EventListener.java
Labels: 3:DevInProgress

#2425 PAYARA-2424 Deployed Applications have an incorrect number of targets
  appserver/admingui/common/src/main/java/fish/payara/admingui/common/handlers/PayaraApplicationHandlers.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/DeployUtil.java
  appserver/admingui/common/src/main/resources/applications/targetListing.jsf
Labels: 3:DevInProgress

#2465 PAYARA-2265 enable ansi colours on all OSs
  nucleus/core/logging/pom.xml
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColor.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColorFormatter.java
  nucleus/packager/nucleus/pom.xml
  nucleus/pom.xml
Labels: 3:DevInProgress

#2463 PAYARA-2384 Missing Log Messages On Boot
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RWLock.java
Labels: 3:DevInProgress

#2464 PAYARA-2366 Revert Production Domain to use JDK 8
  appserver/admin/production_domain_template/src/main/resources/config/domain.xml
  appserver/packager/glassfish-common-web/src/main/resources/bin/asadmin
  appserver/packager/glassfish-common-web/src/main/resources/glassfish/bin/asadmin
Labels: 3:DevInProgress

#2460 PAYARA-2532 Payara Micro Arquillian Container Remove File Watching Code
  appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/file/LogReader.java
  appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/file/StringConsumer.java
  appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/process/ConsoleReader.java
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2458 PAYARA-2535 stateful container initialization order
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
Labels: 4:Ready

#2462 PAYARA-2440 Refactor Pretty Date Format (Payara 5 merge)
  appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/PayaraUtilHandlers.java
Labels: 3:DevInProgress

#2468 PAYARA-2544 Increment version numbers to m3
  appserver/extras/arquillian-containers/payara-client-ee7/pom.xml
  appserver/extras/arquillian-containers/payara-client-ee8/pom.xml
  appserver/extras/arquillian-containers/payara-common/pom.xml
  appserver/extras/arquillian-containers/payara-embedded/pom.xml
  appserver/extras/arquillian-containers/payara-managed/pom.xml
  appserver/extras/arquillian-containers/payara-micro/pom.xml
  appserver/extras/arquillian-containers/payara-remote/pom.xml
  appserver/extras/arquillian-containers/pom.xml
Labels: 3:DevInProgress

#2453 PAYARA-2430 fixes #2305 ManagedExecutorService does not execute tasks…
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/EnableCommand.java
Labels: 3:DevInProgress

#2474 PAYARA-2552 Random initial port for Arquillian Micro connector
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2452 PAYARA-2523 Handle some simple mistakes when specifying domain cluster mode
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/DomainDiscoveryService.java
Labels: 3:DevInProgress

#2455 PAYARA-2492 added options to unpack jars when Payara Micro is used programmatically
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
Labels: 3:DevInProgress

#2456 PAYARA-2538 Add payara-executor-service-configuration tags into domai…
  appserver/admin/gf_template/src/main/resources/config/domain.xml
  appserver/admin/production_domain_template/src/main/resources/config/domain.xml
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
Labels: 3:DevInProgress

#2454 PAYARA-2422 Fix IllegalStateException in the Edit Application page on saving
  appserver/admingui/common/src/main/resources/applications/edit.inc
Labels: 3:DevInProgress

#2476 PAYARA-2554 Fix for NPE in concurrency request tracing
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
Labels: 3:DevInProgress

#2475 PAYARA-2553 Timeout option for Arquillian Micro connector
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2423 PAYARA-2116 restart-instance/restart-local-instance doesn't synchronize when secure admin is enabled
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/LocalStrings.properties
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartInstanceCommand.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/RestartLocalInstanceCommand.java
Labels: 3:DevInProgress

#2461 PAYARA-2329 Javadoc fix
  nucleus/pom.xml
  pom.xml
Labels: 3:DevInProgress

#2451 PAYARA-2536 better concurrency handling for listeners
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/cluster/PayaraCluster.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/eventbus/EventBus.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/eventbus/TopicListener.java
Labels: 3:DevInProgress

#2449 PAYARA-2508 Log file doesn't display logs on an upgraded domain
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/LogService.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/ServerTags.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/logging/UpgradeLogging.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/Constants.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingPropertyNames.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java
Labels: 3:DevInProgress, Action Required

#2481 PAYARA-2555 Micro Arquillian Container Doesn't Allow Spaces In Arguments
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
  appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Labels: 3:DevInProgress

#2483 PAYARA-2148 Transactional CDI2
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedBean.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedCDIEventHelperImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedCDIEventPayload.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedCDIUtil.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedContextExtension.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedContextImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalExtension.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorBase.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorMandatory.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorNever.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorNotSupported.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequired.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequiresNew.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorSupports.java
  appserver/web/weld-integration/src/test/java/org/glassfish/cdi/transaction/InvocationContext.java
  appserver/web/weld-integration/src/test/java/org/glassfish/cdi/transaction/TransactionalAnnotationTest.java
Labels: 3:DevInProgress

#2482 Master merge 28/02/2018
  .gitignore
  appserver/admingui/common/src/main/resources/applications/edit.inc
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
  appserver/ejb/ejb-connector/src/main/java/org/glassfish/ejb/config/EjbContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java
  appserver/extras/arquillian-containers/payara-common/dependency-reduced-pom.xml
  appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  appserver/packager/appserver-base/src/main/docs/README.txt
  appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigProducer.java
  appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/RetryInterceptor.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/GetMetricsConfigurationCommand.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/SetMetricsConfigurationCommand.java
  appserver/payara-appserver-modules/zendesk-support/src/main/java/fish/payara/appserver/zendesk/admin/SetZendeskSupportConfigurationCommand.java
  appserver/payara-appserver-modules/zendesk-support/src/main/java/fish/payara/appserver/zendesk/config/ZendeskSupportConfiguration.java
  appserver/web/web-core/src/main/resources/org/apache/catalina/core/mbeans-descriptors.xml
  appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/LogService.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/ServerTags.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/logging/UpgradeLogging.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/LocalStrings.properties
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartInstanceCommand.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/RestartLocalInstanceCommand.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/AMXStartupService.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigLoader.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/Constants.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingPropertyNames.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java
  nucleus/core/logging/pom.xml
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColor.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColorFormatter.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java
  nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/EnableCommand.java
  nucleus/packager/nucleus/pom.xml
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/eventbus/EventBus.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/GetConfigOrdinal.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/SetConfigOrdinal.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ApplicationConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ClusterConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ConfigConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/DomainConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/JNDIConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ModuleConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/SecretsDirConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ServerConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/MicroprofileConfigConfiguration.java
  nucleus/pom.xml
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/CreateJACCProvider.java
  pom.xml
Labels: 3:DevInProgress
