Repository payara/Payara, pull requests merged in 2019-03, with the labels that each got.

#3701 QA-3 Sonar PR analysis
  Jenkinsfile
Labels: DO NOT MERGE

#3835 Revert "QA-3 Sonar PR analysis"
  Jenkinsfile
Labels: 3:DevInProgress

#3838 Jenkins dev
  Jenkinsfile
  README.md
  appserver/admin/admin-core/src/main/java/com/sun/enterprise/admin/UpgradeService.java
Labels: 3:DevInProgress

#3843 PAYARA-3539 Small cleanup cluster package - sweep 2
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/BootstrapSecureAdminCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ClusterCommandHelper.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CommandRunnable.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/Constants.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CopyConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeImplicitCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeSshCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateRemoteNodeCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteInstanceCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteNodeConfigCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteNodeRemoteCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/DeleteNodeSshCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ExportSyncBundle.java
Labels: 3:DevInProgress

#3846 PAYARA-3682 Increase sleep time to ensure new manifest has later timestamp
  appserver/appclient/client/acc-standalone/fixup.xml
Labels: 3:DevInProgress

#3848 PAYARA-3686 unable to save the Default Principal in the Sercurity Ser…
  appserver/admingui/common/src/main/resources/security/securityAttrs.inc
Labels: 3:DevInProgress

#3798 PAYARA-3666 Fixes for issues found by tests for new health check as-admin commands
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckConfiguration.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceConfiguration.java
  nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceNotifierConfiguration.java
  nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/domain/NotifierExecutionOptionsFactoryStore.java
Labels: payara-micro

#3780 PAYARA-3516-Upgrade-hibernate-validator-to-5.4.3.Final-Payara4
  appserver/extras/payara-micro/payara-micro-microprofile-distribution/pom.xml
  appserver/orb/orb-connector/pom.xml
  appserver/packager/glassfish-jcdi/pom.xml
  appserver/resources/resources-connector/pom.xml
  nucleus/admin/rest/rest-service/pom.xml
  nucleus/core/kernel/pom.xml
  nucleus/packager/nucleus-hk2/pom.xml
  nucleus/pom.xml
Labels: v:Payara-4

#3854 Fixed missing pom refactor [PAYARA-3563]
  appserver/packager/glassfish-ejb/pom.xml
  nucleus/admin/template/pom.xml
Labels: 3:DevInProgress

#3842 PAYARA-3536 JDK 11 build compatible with Quicklook tests
  appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/ACCAgentClassLoader.java
  appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/packageappclient/PackageAppClient.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/CLIBootstrap.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/JWSAdapterManager.java
  appserver/deployment/javaee-core/src/main/java/org/glassfish/javaee/core/deployment/JavaEEDeployer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/StaticRmiStubGenerator.java
  appserver/installer/src/main/java/org/openinstaller/provider/conf/InstallationConfigurator.java
  appserver/packager/glassfish-common-web/pom.xml
  appserver/pom.xml
  appserver/tests/quicklook/build.xml
  appserver/tests/quicklook/ejb/mdb/src/test/mdb/MDBTests.java
  appserver/tests/quicklook/gfproject/build-impl.xml
  appserver/tests/quicklook/pom.xml
  appserver/web/war-util/src/main/java/org/glassfish/web/util/IntrospectionUtils.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/collections/ManifestUtils.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/MainHelper.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/GlassFishMainActivator.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/common/PropsFileActionReporter.java
  nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Ssl.java
  nucleus/pom.xml
Labels: JDK-11+

#3856 Revert "QA-171 Ignoring test until fixed"
  appserver/tests/quicklook/testng/testng_gd.xml
Labels: 3:DevInProgress

#3857 Update Jenkinsfile-Nightly
  Jenkinsfile-Nightly
Labels: 3:DevInProgress

#3853 Payara-3419: Support deploying timers to deployment group and non-persistent timer service
  appserver/admingui/ejb/src/main/resources/configuration/ejbContainerTimerService.jsf
  appserver/admingui/ejb/src/main/resources/org/glassfish/ejb/admingui/Strings.properties
  appserver/ejb/ejb-connector/src/main/java/org/glassfish/ejb/config/EjbTimerService.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbDeployer.java
Labels: 3:DevInProgress

#3859 PAYARA-3493: Upgrade eclipselink to 2.7.4.payara-p2
  appserver/pom.xml
Labels: 3:DevInProgress

#3837 PAYARA-3386: Update login.conf with login module
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/PropertyList.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/SecurityHandler.java
  appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties
  appserver/admingui/common/src/main/resources/security/realms/realmAttrs.inc
  appserver/admingui/common/src/main/resources/security/realms/realmButtons.inc
  appserver/admingui/common/src/main/resources/security/realms/realmjs.inc
  nucleus/security/core/src/main/java/com/sun/enterprise/security/BaseRealm.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/AbstractStatefulRealm.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/Realm.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/CreateAuthRealm.java
Labels: 3:DevInProgress

#3871 [PAYARA-3704] - removed unecessary class duplications
  appserver/ejb/ejb-http-remoting/admin/src/main/java/fish/payara/ejb/rest/admin/DisableEjbInvokerCommand.java
  appserver/ejb/ejb-http-remoting/admin/src/main/java/fish/payara/ejb/rest/admin/EnableEjbInvokerCommand.java
Labels: 3:DevInProgress

#3866 PAYARA-3660: Supply Common Classloader as locator
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ClassloaderResourceLocatorAdapter.java
Labels: 3:DevInProgress

#3864 PAYARA-3540: Use no-fork javadoc invocation and package the jar manually
  pom.xml
Labels: 3:DevInProgress

#3874 PAYARA-3692 remove Space at the end of MysqlDataSource
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/ds.properties
Labels: 3:DevInProgress

#3867 PAYARA-3708 Implemented fixes for JLine Logging
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java
Labels: 3:DevInProgress
