Repository payara/Payara, pull requests merged in 2019-02, with the labels that each got.

#3508 Prevent cpu wastage when not logging to file
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
Labels: community-contribution

#3599 PAYARA-3391 Upgrade maven-jar-plugin to 3.1.1 (Payara 4.x)
  appserver/javaee-api/pom.xml
  nucleus/cluster/gms-adapter/pom.xml
  nucleus/pom.xml
Labels: Action Required

#3452 PAYARA-3262 dont create a new response in the jaxrs container exception mapper - Payara4
  appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingExceptionMapper.java
Labels: Action Required

#3690 PAYARA-2890 HTTP/2 Server Push Issues
  nucleus/pom.xml
Labels: v:Payara-5

#3632 PAYARA-3438: Improve usability MP Health endpoint as readinessProbe
  appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
Labels: Action Required

#3715 PAYARA-3028 Fix remote monitoring of instances from the admin console
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/RestAdapter.java
  nucleus/pom.xml
Labels: v:Payara-5

#3695 Add log property that disables redirection of standard streams to log
  appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf
  appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties
  nucleus/core/logging/pom.xml
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/test/domain/config/logging.properties
  nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LogManagerServiceTest.java
Labels: CLA, community-contribution

#3738 Add a newline at the end
  appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/payara-boot.properties
Labels: community-contribution

#3737 Fix typo
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/NameGenerator.java
Labels: community-contribution

#3713 PAYARA-3490 Code level improvements for payara micro argument and property parsing
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
Labels: payara-micro

#3698 PAYARA-3160 Minimum Log File Size Error Ignored - Payara4 Part 2
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
Labels: v:Payara-4

#3766 PAYARA-3373 Certificate Realms With Custom JCE Provider Still Raise Exceptions - Payara4
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/LoginContextDriver.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
Labels: v:Payara-4

#3752 PAYARA-3318 Restrict permitted HTTP method for FORM based auth (Payara p4.x)
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
Labels: v:Payara-4

#3687 PAYARA-3361 Upgrade Mojarra to Jakarta
  appserver/admin/gf_template/src/main/resources/config/default-web.xml
  appserver/admin/gf_template_web/src/main/resources/config/default-web.xml
  appserver/admin/production_domain_template/src/main/resources/config/default-web.xml
  appserver/admin/production_domain_template_web/src/main/resources/config/default-web.xml
  appserver/admingui/common/pom.xml
  appserver/admingui/pom.xml
  appserver/extras/javaee/manifest-jar/pom.xml
  appserver/javaee-api/javax.javaee-api/pom.xml
  appserver/javaee-api/javax.javaee-web-api/pom.xml
  appserver/javaee-api/pom.xml
  appserver/jdbc/admin/src/test/resources/DomainTest.xml
  appserver/packager/glassfish-jsf/pom.xml
  appserver/pom.xml
  appserver/tests/embedded/maven-plugin/jsftest/pom.xml
  appserver/tests/embedded/maven-plugin/pom.xml
  appserver/tests/embedded/web/web-war/test/pom.xml
  appserver/web/gf-weld-connector/pom.xml
  appserver/web/jsf-connector/pom.xml
  appserver/web/jsf-connector/src/main/resources/META-INF/services/org.glassfish.faces.integration.GlassFishInjectionProvider
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java
  appserver/web/weld-integration/pom.xml
  nucleus/common/common-util/src/test/resources/v2domain.xml
  nucleus/core/kernel/src/test/resources/DomainTest.xml
Labels: MERGE CONFLICT, v:Payara-5

#3767 PAYARA-3373 Certificate Realms With Custom JCE Provider Still Raise Exceptions
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
Labels: v:Payara-5

#3770 QA-180 Fixed new MicroProfile goals.
  Jenkinsfile-MicroProfile
Labels: v:Payara-5

#3790 PAYARA-3520 Update Mojarra to 2.3.9.payara-p2
  appserver/pom.xml
Labels: v:Payara-5

#3792 PAYARA-3438: Improve usability MP Health endpoint as readinessProbe - Payara4
  appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
Labels: v:Payara-4

#3797 PAYARA-3387 Updated Metro to 2.4.3.payara-p1
  appserver/pom.xml
Labels: v:Payara-5
