Repository payara/Payara, pull requests merged in 2019-07, with the labels that each got.

#4034 PAYARA-3911 Fix domain.xml java-home is not honored in version-specific jvm-options (#4025)
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java
Labels: CLA, community-contribution

#3799 PAYARA-3824 Use KeyID from JWT header to find public key in JSON Web Key Set
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
Labels: Action Required, CLA, community-contribution

#4074 PAYARA-3980 Remove duplicated element 'description'
  appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-ejb-jar_3_1-1.dtd
Labels: CLA, community-contribution

#4094 Ensure that the TimerWrapper references correct EJBTimerService
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerServiceWrapper.java
Labels: CLA, community-contribution

#4038 PAYARA-3919 SonarQube - Iterating on entrySet() instead of keySet() when key and value are needed
  api/payara-api/src/main/java/fish/payara/notification/requesttracing/RequestTraceSpan.java
  appserver/admingui/common/src/main/java/fish/payara/admingui/common/handlers/PayaraPropertiesHandlers.java
  appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/NamedNamingObjectManager.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ApplicationValidator.java
  appserver/deployment/javaee-core/src/main/java/org/glassfish/javaee/core/deployment/ListSubComponentsCommand.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbDescriptor.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbSessionDescriptor.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/util/InterceptorBindingTranslator.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroRuntimeImpl.java
  appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
  appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/BaseAuthConfigFactory.java
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/ClientPipeCloser.java
  appserver/tests/quicklook/amx/src/test/amx/AMXConfigProxyTests.java
  appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishTldProvider.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
  nucleus/admin/monitor/src/main/java/fish/payara/admin/monitor/cli/RestartMonitoring.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/StatusGenerator.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigImpl.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/ConfigBeanJMXSupport.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/SampleImpl.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ModuleInfo.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyService.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/monitor/DeploymentLifecycleStatsProvider.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/exec/ClusterExecutionService.java
  nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/NameGenerator.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ClusterConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
Labels: CLA, community-contribution

#4087 PAYARA-3922 Updated jersey.version to 2.29.payara-p4
  nucleus/pom.xml
Labels: v:Payara-5

#4044 PAYARA-3933 Inconsistent metrics time units
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/writer/JsonMetricWriter.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/writer/PrometheusExporter.java
Labels: CLA, community-contribution
