Repository payara/Payara, pull requests merged in 2019-01, with the labels that each got.

#3545 PAYARA-3031 HTTP/2 Trailer Issue
  nucleus/pom.xml
Labels: v:Payara-5

#3585 PAYARA-3160 Minimum Log File Size Error Ignored
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Config.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/logging/UpgradeLogging.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/LoggingImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/Constants.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfig.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigFactory.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/CollectLogFiles.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/DeleteLogLevel.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/ListLogAttributes.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/ListLoggerLevels.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/LoadDefaultLogAttributes.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/LoadDefaultLogLevels.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogFileFormat.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogLevel.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFilter.java
Labels: v:Payara-5

#3534 PAYARA-546 Allow setting SO_KeepAlive on the server side
  appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/util/IIOPUtils.java
  appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/util/NotServerException.java
  appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IIOPSSLSocketFactory.java
Labels: v:Payara-5

#3629 PAYARA-3160 Minimum Log File Size Error Ignored - Payara4
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Config.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/logging/UpgradeLogging.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/LoggingImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/Constants.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfig.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigFactory.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/CollectLogFiles.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/DeleteLogLevel.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/ListLogAttributes.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/ListLoggerLevels.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/LoadDefaultLogAttributes.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/LoadDefaultLogLevels.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogFileFormat.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogLevel.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFilter.java
Labels: v:Payara-4

#3628 PAYARA-3308 Upgrade PrototypeJS PAYARA4
  appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml
  appserver/pom.xml
Labels: v:Payara-4

#3524 common-util: replacing synchronized classes with their unsynchronized counter parts
  nucleus/common/common-util/src/main/java/com/sun/appserv/util/cache/BaseCache.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/SystemProps.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ExceptionUtil.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/LocalStringManagerImpl.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ObjectAnalyzer.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/StringUtils.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/SystemPropertyConstants.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/i18n/StringManager.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/i18n/StringManagerBase.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/uuid/UuidUtilPadded.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/StringHelper.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/timer/TimerSchedule.java
Labels: community-contribution, v:Payara-5

#3249 Fixing bugs of blocker and major for module JTS for GF
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/iiop/TransactionServerInterceptor.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/AdminUtil.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/CoordinatorLog.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/DefaultTransactionService.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/DelegatedRecoveryManager.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/LogHandle.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RWLock.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryCoordinatorImpl.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/SubCoordinator.java
  appserver/transaction/jts/src/main/java/com/sun/jts/codegen/jtsxa/OTSResourceHelper.java
  appserver/transaction/jts/src/main/java/com/sun/jts/codegen/otsidl/CoordinatorResourceHelper.java
  appserver/transaction/jts/src/main/java/com/sun/jts/codegen/otsidl/JControlHelper.java
  appserver/transaction/jts/src/main/java/com/sun/jts/codegen/otsidl/JCoordinatorHelper.java
  appserver/transaction/jts/src/main/java/com/sun/jts/codegen/otsidl/ResourceStatusHelper.java
  appserver/transaction/jts/src/main/java/com/sun/jts/codegen/otsidl/TransAncestryHelper.java
  appserver/transaction/jts/src/main/java/com/sun/jts/pi/InterceptorImpl.java
Labels: CLA, community-contribution, v:Payara-5
