Repository payara/Payara, pull requests merged in 2019-04, with the labels that each got.

#3878 PAYARA-3464 MicroProfile description does not save
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java
Labels: 3:DevInProgress

#3870 PAYARA-3676 PAYARA-3665 Fix More Asadmin Prompt Issues
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/LoginCommand.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCLICommand.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeAdminPasswordCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/CreateDomainCommand.java
  nucleus/admin/util/pom.xml
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/AsadminTrustManager.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/LocalInstanceCommand.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/SetupLocalDcom.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/SetupSshKey.java
  nucleus/common/common-util/pom.xml
  nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/AsadminSecurityUtil.java
Labels: 3:DevInProgress

#3875 PAYARA-3515 Fix setting authentication realm on Virtual Server with a property
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityDeployer.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
Labels: 3:DevInProgress

#3879 PAYARA-3484 JDK11 Java EE 7 Sample: ejb - remote - Roles Allowed testcase fix
  appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java
  nucleus/pom.xml
Labels: 3:DevInProgress

#3880 PAYARA-3674: Preserve Thread Context Class Loader...
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/ExecutorServicesImpl.java
Labels: 3:DevInProgress

#3869 PAYARA-3670 Logger settings can't be changed from Admin Console
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/LoggingHandlers.java
  appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf
  appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/LogService.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/ServerTags.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/logging/UpgradeLogging.java
  nucleus/admin/template/src/main/resources/config/logging.properties
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/LoggingImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingPropertyNames.java
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java
  nucleus/core/logging/pom.xml
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
  nucleus/core/logging/src/test/domain/config/logging.properties
  nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/GFFilehandlerTest.java
  nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LogEventListenerTest.java
  nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LogManagerServiceTest.java
  nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LoggingPropertiesTest.java
Labels: 3:DevInProgress, v:Payara-5

#3886 PAYARA-3722 - Sonar cleanups in JDKPolicyFileWrapper
  appserver/security/jacc.provider.file/src/main/java/com/sun/enterprise/security/provider/JDKPolicyFileWrapper.java
Labels: 3:DevInProgress

#3890 PAYARA-3743-Upgrade-snakeyaml-to-1.24
  nucleus/pom.xml
Labels: 3:DevInProgress

#3891 PAYARA-3744-Upgrade-MIME-Streaming-Extension-mimepull-to-1.9.11
  nucleus/pom.xml
Labels: 3:DevInProgress

#3892 PAYARA-3668-Update-libpam4j-to-version-1.11
  appserver/packager/external/libpam4j/pom.xml
Labels: 3:DevInProgress

#3901 PAYARA-3754 @Clustered Annotation Doesn't Use Bean Name
  appserver/payara-appserver-modules/payara-micro-cdi/pom.xml
  appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusterScopeContext.java
  appserver/payara-appserver-modules/payara-micro-cdi/src/test/java/fish/payara/micro/cdi/extension/cluster/ClusterScopeContextTest.java
Labels: v:Payara-5

#3916 PAYARA-3780 fix http and https ports in generated openapi
  appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
Labels: community-contribution

#3906 avoid using non-threadsafe XPath as static property
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/CombinedXPath.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/XPathToDeveloperProvidedContentRefs.java
Labels: CLA, community-contribution

#3909 PAYARA-3784 Fixed OpenIdState equals method
  api/payara-api/src/main/java/fish/payara/security/openid/api/OpenIdState.java
  appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
  appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/controller/StateController.java
Labels: CLA, community-contribution
