Repository payara/Payara, pull requests merged in 2021-01, with the labels that each got.

#4997 FISH-765 #4653 Propagate VirtualServer config to WebModule
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
Labels: PR: CLA, Type: Community Contribution

#4441 [FISH-1017] Payara can close JarFile instances used by current URLClassLoaders
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java
Labels: PR: CLA, Status: Accepted, Type: Bug, Type: Community Contribution

#5071 Add appropriate application name to GAV deployments / FISH-1015
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
  appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
Labels: PR: CLA, Type: Community Contribution

#5074 [FISH-759] sort instances in admin console
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ClusterHandler.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java
Labels: PR: CLA, Type: Community Contribution

#5082 5080 Payara logback libs produce NPE / FISH-1007
  appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/activation/ConfigDeployer.java
  appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/activation/MetricsSniffer.java
Labels: PR: CLA, Type: Community Contribution

#5089 FISH-992 Be able to use default values in data source definitions when translating values #5079
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java
  nucleus/admin/config-api/src/test/java/org/glassfish/config/support/TranslatedValueTest.java
Labels: PR: CLA, Status: Accepted, Type: Community Contribution, Type: Enhancement

#5101 [FISH-1019] GlassFishProperties fix by @bhanuunrivalled
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
Labels: PR: CLA, Status: Accepted, Type: Bug, Type: Community Contribution

#5081 [FISH-1018] Out of memory redeploy leaks
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorRuntime.java
  appserver/deployment/javaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarClassLoader.java
  appserver/deployment/javaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarDeployer.java
  appserver/deployment/javaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarLibClassLoader.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/DSManagedConnectionFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ResourceAdapterImpl.java
  appserver/tests/payara-samples/classloader-data-api/pom.xml
  appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceResource.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/InstanceCounter.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
Labels: PR: CLA, Type: Community Contribution

#5007 FISH-788 Support sub-directories for MPCONFIG SecretDirConfigSource. #5006
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/DirConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/PayaraConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/SecretsDirConfigSource.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/DirConfigSourceTest.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/NewTestSuite.java
  nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/SecretsDirConfigSourceTest.java
Labels: PR: CLA, Type: Community Contribution

#5062 FISH-868 JWT public key is cached for a configurable amount of time.
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtPublicKeyStore.java
  appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java
Labels: PR: CLA, Type: Community Contribution
